apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
{% if k3s_traefik_gateway == "true" %}
    providers:
      kubernetesGateway:
        enabled: true
{% endif %}
    ports:
      web:
        redirectTo: 
          port: websecure
          priority: 10
